version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - ./db/:/data/db
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    ports:
      - 4000:4000
    restart: on-failure
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./frontend/.env
  nginx:
    container_name: nginx_proxy
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
