version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - ./mongo_data/:/data/db
  backend:
    build:
      dockerfile: Dockerfile.prod
      context: ./backend
    container_name: backend
    ports:
      - 4000:4000
    restart: on-failure
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
    container_name: frontend
    ports:
      - 8000:8000
    restart: on-failure
    env_file:
      - ./frontend/.env.production
volumes:
  mongo_data:
