version: "3.4"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    ports:
      - 4000:4000
    restart: always
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    image: node:alpine
    container_name: frontend
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./frontend
        target: /srv/app
    tty: true

  nginx:
    container_name: nginx_proxy
    build:
      context: ./proxy
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf