version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - ./db/:/data/db
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: backend
    ports:
      - 4000:4000
    restart: always
    volumes:
      - /app/node_modules
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    container_name: frontend
    ports:
      - 8000:8000
    restart: always
    volumes:
      - /app/node_modules
      - ./frontend/src:/app/src
    env_file:
      - ./frontend/.env.development
  nginx:
    container_name: nginx_proxy
    build:
      dockerfile: Dockerfile.dev
      context: ./proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - frontend
      - backend
    volumes:
      - ./proxy/nginx-dev.conf:/etc/nginx/nginx.conf
