name: Prettier
on:
  push:
    branches:
      - master
      - dev
    paths:
      - "backend/**"
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name:  run Prettier
        run: |
          cd backend
          npm install
          npm run prettier
