name: Deploy to EC2
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: SSH into EC2 and Deploy
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -T -o StrictHostKeyChecking=no ubuntu@143.110.188.165
          cd /home/ubuntu/LeetCode_Tracker
          sudo make down
          git fetch --all 
          git reset --hard origin/staging
          git pull origin staging
          cd backend && npm i
          cd ../frontend && npm i
          cd .. && sudo make all
